### ISSUE TITLE
Cannot read property 'firebase' of undefined

### ISSUE THREAD

**Issue by thiamugb** [thiamugb/testfirebase#1]
Here is my firebase Test i use then in a appp  @EddyVerbruggen

**Comment by thiamugb** [comment]
If you have time for me i used Nativescript-Bluetooth and i want to write to this characterics like.
  await bluetooth.writeWithoutResponse({
    serviceUUID: '1802',
    characteristicUUID: '2a06',
    peripheralUUID: 'CC:27:69:37:14:55',
    value:0x01
  })
i have this error have you a issue @EddyVerbruggen  'Error in Bluetooth.writeWithoutResponse: Error: Expect integer value as a second argument.'

**Comment by EddyVerbruggen** [comment]
How do I reproduce the firebase issue? What are the exact steps?

**Comment by thiamugb** [comment]
Actually firebase init s done.
I have a problem with Bluetooth write value

**Comment by thiamugb** [comment]
Need help for writewithoutresponse value in a characteristics in android 
Have you an issue up to date @EddyVerbruggen

**Comment by thiamugb** [comment]
@sebawita
